service: wedstage-bk-timeline
frameworkVersion: '3.34.0'
configValidationMode: error

plugins:
  - serverless-prune-plugin
  - serverless-domain-manager

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 2
  serverless-offline:
    noPrependStageInUrl: true
  config: ${file(./bk-config/configs.${self:provider.stage}.json)}
  domains:
    prod: api.wedstage.com
    dev: dev-api.wedstage.com
  customDomain:
    # Ex: serverless create_domain --stage dev
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: 'timeline' # indication of backend service
    stage: ${self:provider.stage}
    createRoute53Record: false
  customCors:
    origin: '*'
    headers:
      - platform
      - appversion
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowCredentials: false

provider:
  name: aws
  timeout: 12
  runtime: nodejs14.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: ${self:custom.config.lambdaRole}
  # vpc:
  #   securityGroupIds:
  #     - ${self:custom.config.securityGroup}
  #   subnetIds:
  #     - ${self:custom.config.subnet1}
  #     - ${self:custom.config.subnet2}
  #     - ${self:custom.config.subnet3}
  endpointType: REGIONAL
  deploymentBucket: ${self:provider.stage}-wedstage-serverless-deployments
  environment: ${file(./bk-config/envs.${self:provider.stage}.json)}


functions:
  timeline-bg-tasks:
    timeout: 60
    name: ${self:custom.config.envPrefix}-timeline-bg-tasks
    handler: processor.sns
    events:
      - sns: arn:aws:sns:${self:custom.config.awsRegion}:${self:custom.config.awsAccountId}:${self:custom.config.envPrefix}-timeline-bg-tasks
  timeline-apis:
    name: ${self:custom.config.envPrefix}-timeline-apis
    handler: timelineHandler.invoke
    events:
      - http:
          path: /v1/list
          method: any
          cors: ${self:custom.customCors}
      - http:
          path: /v1/new
          method: post
          cors: ${self:custom.customCors}
      - http:
          path: /v1/{id}
          method: any
          cors: ${self:custom.customCors}
      - http:
          path: /v1/{id}/like
          method: any
          cors: ${self:custom.customCors}
      - http:
          path: /v1/{id}/comment
          method: any
          cors: ${self:custom.customCors}
      - http:
          path: /v1/{id}/likes
          method: get
          cors: ${self:custom.customCors}
      - http:
          path: /v1/{id}/comments
          method: get
          cors: ${self:custom.customCors}


resources:
  Conditions:
    isProd: {"Fn::Equals" : ["${self:provider.stage}", "prod"]}
    isDev: {"Fn::Equals" : ["${self:provider.stage}", "dev"]}
  Resources:
    TimelineBgTasksSNS:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.config.envPrefix}-timeline-bg-tasks